### ISSUE TITLE
Include the data importer in the script

### ISSUE THREAD

**Issue by infinitytec** [runlevel-4/firefly-iii-automation#1]
That would make life easier :)

**Comment by runlevel-4** [comment]
I'll check that out.  Thanks @infinitytec :)

**Comment by runlevel-4** [comment]
@infinitytec This has been completed.  It creates a separate directory next to the firefly-iii directory.  So to access it, you replace **firefly-iii** with **data-importer** in the URL.

Firefly: http://serverip/firefly-iii/public

Data-Importer: http://serverip/data-importer/public

Let me know if you want it inside of the firefly-iii directory.

**Comment by infinitytec** [comment]
Awesome! It seems to be working just fine!

**Comment by runlevel-4** [comment]
You're right, I'll check it out.  It could have something to do with the .env config file.

**Comment by lisim** [comment]
any update on this
Doing some reasearch appears might be an issue with using folders over subdomians

**Comment by RyanHind** [comment]
Any update? This is preventing me from uploading :(

**Comment by infinitytec** [comment]
> Any update? This is preventing me from uploading :(
> 
> Edit: Fixed in the update to 0.9.16

You are seeing it work now?

**Comment by RyanHind** [comment]
Haven't used this in awhile, but yes. After I updated to the above version it worked for me and I was able to upload.

**Comment by infinitytec** [comment]
> Haven't used this in awhile, but yes. After I updated to the above version it worked for me and I was able to upload.

Just updating the data importer?

**Comment by infinitytec** [comment]
OK, I made a PR with updates to the version and that seems to be the solution!
