### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by D1Ck3n** [runlevel-4/firefly-iii-automation#10]
Good day,

i tried your script in a LXC Container with Debian 11 and LAMP. The Script ran successfully but the browser only shows:

Not Found

The requested URL was not found on this server.

**Comment by runlevel-4** [comment]
D1Ck3n,

After the install, and when going through the setup on the webpage, you
have to inject the proper server IP and subfolder into URL
(http://<SERVERIP>/Nextcloud/.....).
I have yet to fix that :/

*- James Edwards*
