### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by EtherForge** [runlevel-4/firefly-iii-automation#15]
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.3.0".
But Composer installed, and i have a PHP 8.3.0.

**Comment by runlevel-4** [comment]
Hi @EtherForge,

Please refer to the official firefly-iii documentation for installing the docker image.  I will be retiring this script.

https://docs.firefly-iii.org/how-to/firefly-iii/installation/docker/

**Comment by EtherForge** [comment]
Nooooo dude <:o
RIP your script, but you're still great for trying and doing it!

**Comment by runlevel-4** [comment]
Yeah it worked a while back, but I'm sure the app has gone through some changes, and I never really accounted for the importer piece.

I have been a bit dormant on GitHub but I will be getting back into keeping my other installers up to date :)
