### ISSUE TITLE
Include locales

### ISSUE THREAD

**Issue by infinitytec** [runlevel-4/firefly-iii-automation#3]
Include locales to get rid of the banner warning.

I think these should do, at least with Ubuntu:
`locale-gen en_US.utf8
locale-gen nl_NL.utf8
update-locale`

Then restart PHP (unless maybe done before. I just figured out the fix so I'm not entirely sure this is how it works.)

**Comment by runlevel-4** [comment]
@infinitytec Which banner are you referring to?

**Comment by infinitytec** [comment]
It was about this error: https://docs.firefly-iii.org/firefly-iii/advanced-installation/locales/#missing-packages-or-configuration

**Comment by infinitytec** [comment]
My PR should make this at least less of an issue.
