### ISSUE TITLE
Add curl to installed packages list

### ISSUE THREAD

**Issue by Kathelll** [runlevel-4/firefly-iii-automation#5]
The Ubuntu images installed from official LXD repositories do not have Curl package installed by default,
which results in a failure to install Composer and subsequently the whole script fails.

I suggest to add Curl to the list of installed packages during the script execution.

**Comment by runlevel-4** [comment]
@Kathelll Can you give it a try now?  I added curl to the list of installers.

**Comment by infinitytec** [comment]
I'd suggest closing this because it seems to install OK for me.
