### ISSUE TITLE
Update Firefly and Data-importer versions

### ISSUE THREAD

**Issue by kodamaChameleon** [runlevel-4/firefly-iii-automation#6]
sudo composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 5.7.15

sudo composer create-project firefly-iii/data-importer --no-dev --prefer-dist data-importer 0.9.17

**Comment by spencewenski** [comment]
Related: #7, though there's another newer version since this issue was opened.

**Comment by kodamaChameleon** [comment]
Duplicate of #7.
