### ISSUE TITLE
Create update script

### ISSUE THREAD

**Issue by infinitytec** [runlevel-4/firefly-iii-automation#9]
A separate script (or, better yet, auto-detecting a current installation and a prompt) would make updating the system easier. Running the install script will wipe out all data currently.

**Comment by infinitytec** [comment]
Looks like version 6.0 was released as of a few hours ago. If I get a chance I'll try building a new function onto the script to look for existing installations and prompt to upgrade.

**Comment by runlevel-4** [comment]
@infinitytec I went ahead and merged.
